version: '3.8'
services:
  hello-frontend:
    image: frontend
    environment:
      - REACT_APP_BACKEND_URL="http://localhost"
    build: 
      context: ./hello-frontend
      dockerfile: Dockerfile

  cache:
    image: redis
    container_name: redis
    restart: unless-stopped
    command: redis-server

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres

  hello-backend:
    image: backend
    environment:
      - REQUEST_ORIGIN="http://localhost"
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    build: 
      context: ./hello-backend
      dockerfile: Dockerfile

  nginx:
    image: nginx
    container_name: nginx
    ports:
    - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
