version: '3.8'
services:
  cache:
    image: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data
  app:
    image: waleedsamy/hello-world-expressjs-docker:latest
    ports:
      - '8080:8080'
    container_name: example-backend
    environment:
      - REDIS_HOST=cache
volumes:
  cache:
    driver: local 