version: '3.8'
services:
  hello-frontend:
    image: node:16.0.0
    working_dir: /usr/src/app
    environment:
      - REACT_APP_BACKEND_URL="http://localhost:8080/"
    build: .
    ports:
      - 5000:5000
    command: >
      sh -c "npm init -y &&
            npm install &&
            RUN npm run build &&
            RUN npm install -g serve"

  cache:
    image: redis
    container_name: redis
    restart: unless-stopped
    command: redis-server

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres

  hello-backend:
    image: golang:1.16
    working_dir: /usr/src/app
    environment:
      - REQUEST_ORIGIN="http://localhost:5000"
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 8080:8080
    command: >
      sh -c "
      go build &&
            ./server"
